services:
  user_service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    ports:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy
 
    environment:
      - DB_URL=postgres://app:app@postgres:5432/auth_service_db
      - Card_DB_URL=postgres://app:app@postgres:5432/payment_service_db
      - LEDGER_ADDR=ledger_service:50051
    restart: unless-stopped
  payment_service:
    build: 
      context: .
      dockerfile: ./payment_service/Dockerfile
    ports:
      - "8001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_URL=postgres://app:app@postgres:5432/payment_service_db

    restart: unless-stopped
  auth_service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    ports:
      - "8002"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_URL=postgres://app:app@postgres:5432/auth_service_db
      - Secret_Token=hfbndijskm
    
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    ports:
      - "1234:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - transaction_service
      - user_service
      - auth_service
      - payment_service
      - ledger_service

  otel-collector:
    image: otel/opentelemetry-collector:0.79.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docs/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4318:4318" # OTLP HTTP
      - "4317:4317" # OTLP gRPC

  jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686"
      - "14268:14268"
    restart: unless-stopped


  transaction_service:
    build: 
      context: .
      dockerfile: ./transaction_service/Dockerfile
    ports:
      - "8003"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_url=postgres://app:app@postgres:5432/auth_service_db
      - Port=8003
      - LEDGER_ADDR=ledger_service:50051
    restart: unless-stopped
  ledger_service:
    build:
      context: .
      dockerfile: ./ledger_service/Dockerfile
    ports:
      - "50051"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_url=postgres://app:app@postgres:5432/ledger_service_db
    restart: unless-stopped
  postgres:
    image: postgres:16-alpine
    container_name: postgresDB
    restart: unless-stopped
    environment:
      - POSTGRES_DB=pocketpay
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./db/init:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-pocketpay} -h localhost"]
      interval: 3s
      timeout: 5s
      retries: 20
volumes:
  pgdata: