events { worker_connections 1024; }

http {
    upstream user_service {
        server user_service:8000;
    }
    upstream payment_service {
        server payment_service:8001;
    }
    upstream auth_service {
        server auth_service:8002;
    }
    upstream transaction_service {
        server transaction_service:8003
    }

    server {
        listen 80;

        location = /users {
            return 301 /users/;
        }

        location /users/ {
            proxy_pass http://user_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 5s;
            proxy_read_timeout 30s;
        }

        location = /payments {
            return 301 /payments/;
        }
        location /payments/ {
            proxy_pass http://payment_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location = /auth {
            return 301 /auth/;
        }
        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location = /transaction {
            return 301 /transaction/
        }
        location /transaction/ {
            proxy_pass http://transaction_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location = /health {
            return 200 'ok';
            add_header Content-Type text/plain;
        }
    }
}
